### PR TITLE
new highlighter, pics, foldings

### PR DESCRIPTION
**Pull request by andymtorres**
New theme to support CM, UTX, ETX and FTX files. 
Basic snippets for CM files
Basic foldings for FTX files

### CODE REVIEW

**Comment by illnr** [comment]
Nice work! Thank you!

**Comment by illnr** [comment]
Just pushed to VSCode Marketplace ([https://marketplace.visualstudio.com/items?itemName=fabi.fanuc-karel-syntax](https://marketplace.visualstudio.com/items?itemName=fabi.fanuc-karel-syntax)). I had to revert publisher name, because it is used by vsce publish tool. But you/I can put credits if you like.

**Comment by andymtorres** [comment]
No problem! thank you 👍

**Comment by illnr** [comment]
@andymtorres The [commits](https://github.com/iBaff/vscode-fanuc-karel/pull/5/commits) from this and the [last merge](https://github.com/iBaff/vscode-fanuc-karel/pull/3/commits) were made by "Molina Frank" and thus you are not listed as a [Contributor](https://github.com/iBaff/vscode-fanuc-karel/graphs/contributors). Maybe your git is configured to use another name/mail than GitHub expects?

**Comment by andymtorres** [comment]
Hi,
Thanks for telling me this. But I am Molina Frank. Molina Torres is my maiden name. ^^

Andrea

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by illnr** [comment]
@all-contributors please add andymtorres for code

**Pull request merged**
